-- -----------------------------------------------------------------------------
-- SUPABASE INITIALIZATION SCHEMA FOR ARA NEUROPOST (MVP)
-- -----------------------------------------------------------------------------
-- Autor: Jack-SafeRefactor
-- Descripción: Esquema base con RLS minimalista para MVP.
-- Dependencias: auth.users (Supabase Auth)
-- -----------------------------------------------------------------------------

-- 1. TABLA: PROJECTS
-- Entidad raíz anclada a auth.users.
create table public.projects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz default now()
);

-- Index para optimizar RLS
create index on public.projects(owner_id);

-- 2. TABLA: CAMPAIGNS
-- Agrupador lógico de contenido.
create table public.campaigns (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  objective text,
  tone text,
  status text default 'active',
  created_at timestamptz default now()
);

-- Index para optimizar JOINs y RLS
create index on public.campaigns(project_id);

-- 3. TABLA: POSTS
-- Unidad central de contenido.
create table public.posts (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  campaign_id bigint references public.campaigns(id),
  title text,
  content_text text,
  hashtags text,
  status text default 'pending',
  platform text default 'linkedin',
  scheduled_for timestamptz,
  published_at timestamptz,
  created_at timestamptz default now()
);

-- Index para optimizar JOINs y RLS
create index on public.posts(project_id);
create index on public.posts(campaign_id);

-- 4. TABLA: CONNECTED_ACCOUNTS
-- Credenciales OAuth encriptadas.
create table public.connected_accounts (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  provider text default 'linkedin',
  external_id text not null,
  provider_name text,
  access_token text not null, -- Encriptado en backend
  refresh_token text,         -- Encriptado en backend
  expires_at timestamptz,
  active boolean default true,
  created_at timestamptz default now()
);

-- Index para optimizar JOINs y RLS
create index on public.connected_accounts(project_id);

-- -----------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) CONFIGURATION
-- -----------------------------------------------------------------------------

-- Activar RLS en todas las tablas
alter table public.projects enable row level security;
alter table public.campaigns enable row level security;
alter table public.posts enable row level security;
alter table public.connected_accounts enable row level security;

-- POLÍTICA 1: PROJECTS (OWNER ACCESS)
-- El usuario solo puede ver/editar proyectos donde es el owner.
create policy "Projects owner access"
on public.projects
for all
using (auth.uid() = owner_id);

-- POLÍTICA 2: CAMPAIGNS (INHERITED ACCESS)
-- Acceso si el usuario es owner del proyecto padre.
create policy "Campaigns project scoped access"
on public.campaigns
for all
using (
  exists (
    select 1 from public.projects
    where projects.id = campaigns.project_id
    and projects.owner_id = auth.uid()
  )
);

-- POLÍTICA 3: POSTS (INHERITED ACCESS)
-- Acceso si el usuario es owner del proyecto padre.
create policy "Posts project scoped access"
on public.posts
for all
using (
  exists (
    select 1 from public.projects
    where projects.id = posts.project_id
    and projects.owner_id = auth.uid()
  )
);

-- POLÍTICA 4: CONNECTED_ACCOUNTS (INHERITED ACCESS)
-- Acceso si el usuario es owner del proyecto padre.
create policy "Accounts project scoped access"
on public.connected_accounts
for all
using (
  exists (
    select 1 from public.projects
    where projects.id = connected_accounts.project_id
    and projects.owner_id = auth.uid()
  )
);

-- -----------------------------------------------------------------------------
-- FIN DEL SCRIPT
-- -----------------------------------------------------------------------------
